version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
    - method: pip
      packages:
        - mkdocs>=1.6.1
        - mkdocstrings[python]>=0.24.0
        - mkdocs-material>=9.0.0
        - pymdown-extensions>=10.0.0

formats:
  - pdf
  - epub
  - html

